//===----------------------------------------------------------------------===//
//
// Part of the Viper project, under the GNU GPL v3.
// See LICENSE for license information.
//
//===----------------------------------------------------------------------===//
///
/// @file Sema_Runtime.cpp
/// @brief Runtime function registration for the Zia semantic analyzer.
///
/// This file includes the auto-generated runtime function definitions from
/// ZiaRuntimeExterns.inc, which is generated by rtgen from runtime.def.
///
//===----------------------------------------------------------------------===//

#include "frontends/zia/Sema.hpp"

namespace il::frontends::zia
{

void Sema::initRuntimeFunctions()
{
    // Auto-generated from src/il/runtime/runtime.def by rtgen.
    // This registers all Viper.* namespace functions as extern symbols in scope.
    // Using defineExternFunction() ensures they work exactly like user-defined
    // namespaced functions, with isExtern=true for the lowerer.
#include "il/runtime/ZiaRuntimeExterns.inc"
}

} // namespace il::frontends::zia
