if(NOT DEFINED ILC)
  message(FATAL_ERROR "ILC not set")
endif()
if(NOT DEFINED IL_FILE)
  message(FATAL_ERROR "IL_FILE not set")
endif()
if(NOT DEFINED GOLDEN)
  message(FATAL_ERROR "GOLDEN not set")
endif()
if(NOT DEFINED PASSES)
  set(PASSES "constfold,peephole")
endif()
set(OUT_FILE "${CMAKE_CURRENT_BINARY_DIR}/out.il")
execute_process(COMMAND ${ILC} il-opt ${IL_FILE} -o ${OUT_FILE} --passes ${PASSES} RESULT_VARIABLE res)
if(NOT res EQUAL 0)
  message(FATAL_ERROR "il-opt failed")
endif()
file(READ ${OUT_FILE} out)
file(READ ${GOLDEN} expected)
string(STRIP "${out}" out)
string(STRIP "${expected}" expected)
if(NOT out STREQUAL expected)
  message(FATAL_ERROR "IL mismatch\nExpected: ${expected}\nGot: ${out}")
endif()
