//===----------------------------------------------------------------------===//
//
// Part of the Viper project, under the MIT License.
// See LICENSE for license information.
//
//===----------------------------------------------------------------------===//
//
// This file declares the runtime library's mathematical function API, providing
// portable implementations of standard math operations for BASIC programs. These
// functions are invoked from IL code generated by the BASIC frontend when users
// call built-in math functions like SIN, COS, SQR, ABS, SGN, etc.
//
// The runtime math API serves several purposes:
//
// 1. Platform Abstraction: Provides consistent math behavior across all targets
//    (x86-64, ARM, WebAssembly) by wrapping platform-specific math libraries
//    with a uniform C ABI.
//
// 2. Error Handling: Implements BASIC's error semantics for domain errors, overflow,
//    and invalid operations. Unlike C's math library which uses errno or NaN,
//    these functions trap on error conditions, allowing BASIC's ON ERROR mechanism
//    to catch and handle exceptional cases.
//
// 3. Type Specialization: Provides both integer and floating-point variants for
//    functions like abs() and sgn(), matching BASIC's type system requirements
//    and avoiding unnecessary conversions.
//
// Mathematical Functions Provided:
//
// Transcendental Functions:
// - Trigonometric: rt_sin, rt_cos, rt_tan, rt_atan
// - Exponential: rt_exp, rt_log
// - Power/Root: rt_sqrt (in rt_numeric.h as rt_sqrt_chk_f64)
//
// Numeric Functions:
// - Sign: rt_sgn_i64 (returns -1/0/+1), rt_sgn_f64
// - Absolute value: rt_abs_i64, rt_abs_f64
// - Rounding: rt_floor, rt_ceil (explicit rounding direction)
//
// Design Philosophy:
// These functions intentionally mirror C99 math library signatures for easy
// implementation on platforms with standard math support. The rt_ prefix
// distinguishes runtime functions from system functions and provides a clear
// namespace for runtime APIs.
//
// Error Handling Contract:
// All functions that can encounter domain errors (sqrt of negative, log of zero)
// have "_chk" variants that validate inputs and trap on errors. The basic
// functions declared here assume valid inputs for performance; checked variants
// are in rt_numeric.h.
//
// Implementation Notes:
// Most functions are thin wrappers around platform math libraries (libm on Unix,
// MSVCRT on Windows). The wrappers ensure consistent behavior across platforms
// and provide the extern "C" ABI required by IL's calling convention.
//
// Precision and Accuracy:
// All floating-point operations use IEEE-754 double precision (f64 in IL).
// BASIC's SINGLE type is currently promoted to DOUBLE during lowering, so all
// runtime math operates at double precision.
//
//===----------------------------------------------------------------------===//

#pragma once

#include <stdint.h>

#ifdef __cplusplus
extern "C"
{
#endif

    double rt_sqrt(double);
    double rt_floor(double);
    double rt_ceil(double);
    double rt_sin(double);
    double rt_cos(double);
    double rt_tan(double);
    double rt_atan(double);
    double rt_exp(double);
    double rt_log(double);
    long long rt_sgn_i64(long long);
    double rt_sgn_f64(double);
    long long rt_abs_i64(long long);
    double rt_abs_f64(double);

#ifdef __cplusplus
}
#endif
