//===----------------------------------------------------------------------===//
//
// Part of the Viper project, under the MIT License.
// See LICENSE for license information.
//
//===----------------------------------------------------------------------===//
// File: include/viper/diag/BasicDiag.hpp
// Purpose: Auto-generated catalog of BASIC diagnostic identifiers and helpers.
// Key invariants: Enum values and lookup functions stay in sync with diagnostics.yaml.
// Ownership/Lifetime: Provides views over static tables.
// Links: scripts/spec/diagnostics.yaml
//
// NOTE: This file is auto-generated by scripts/gen_diagnostics.py. Do not edit manually.
#pragma once

#include "support/diagnostics.hpp"
#include <initializer_list>
#include <string>
#include <string_view>

namespace il::frontends::basic::diag
{

enum class BasicDiagId
{
    BASIC_UNDECLARED_VARIABLE,
    BASIC_UNKNOWN_ARRAY,
    BASIC_NOT_AN_ARRAY,
    BASIC_INDEX_TYPE_MISMATCH,
    BASIC_INDEX_NARROWING_FLOAT,
    BASIC_INDEX_OUT_OF_BOUNDS,
    BASIC_ASSIGN_NARROWING_FLOAT_TO_INT,
    BASIC_ARRAY_ASSIGN_NARROWING_FLOAT_TO_INT,
    BASIC_ARRAY_SIZE_NARROWING_FLOAT_TO_INT,
    BASIC_ARRAY_SIZE_NON_NEGATIVE,
    Count,
};

struct Replacement
{
    std::string_view key;
    std::string_view value;
};

std::string_view getFormat(BasicDiagId id);
il::support::Severity getSeverity(BasicDiagId id);
std::string formatMessage(BasicDiagId id, std::initializer_list<Replacement> replacements = {});

} // namespace il::frontends::basic::diag

