DIM B AS BOOLEAN
LET B = TRUE
PRINT NOT FALSE
PRINT TRUE ANDALSO FALSE
PRINT TRUE AND FALSE
PRINT TRUE ORELSE FALSE
PRINT TRUE OR FALSE
PRINT 1 = 2 OR 3 = 4
PRINT NOT TRUE AND FALSE
PRINT TRUE OR FALSE AND TRUE
PRINT NOT (TRUE ORELSE FALSE)
PRINT TRUE ORELSE FALSE ANDALSO TRUE
