if(NOT DEFINED ILC)
  message(FATAL_ERROR "ILC not set")
endif()
if(NOT DEFINED BAS_FILE)
  message(FATAL_ERROR "BAS_FILE not set")
endif()
if(NOT DEFINED EXPECT)
  message(FATAL_ERROR "EXPECT not set")
endif()
execute_process(COMMAND ${ILC} front basic -emit-il ${BAS_FILE} RESULT_VARIABLE res OUTPUT_VARIABLE out ERROR_VARIABLE out)
if(res EQUAL 0)
  message(FATAL_ERROR "expected non-zero exit")
endif()
if(NOT out MATCHES "${EXPECT}")
  message(FATAL_ERROR "expected message not found: ${EXPECT}\\n${out}")
endif()
