if(NOT DEFINED ILC)
  message(FATAL_ERROR "ILC not set")
endif()
if(NOT DEFINED BAS_FILE)
  message(FATAL_ERROR "BAS_FILE not set")
endif()
if(NOT DEFINED GOLDEN)
  message(FATAL_ERROR "GOLDEN not set")
endif()
file(WRITE script.txt "continue\n")
execute_process(COMMAND ${ILC} front basic -run ${BAS_FILE} --break ${BAS_FILE}:2 --debug-cmds script.txt
                OUTPUT_FILE out.txt ERROR_FILE err.txt RESULT_VARIABLE r2)
if(NOT r2 EQUAL 0)
  message(FATAL_ERROR "execution failed")
endif()
file(READ err.txt ERR)
string(STRIP "${ERR}" ERR_STR)
if(NOT ERR_STR STREQUAL "[BREAK] fn=@main blk=L20 reason=src BreakSrcLine.bas:2")
  message(FATAL_ERROR "missing break")
endif()
file(READ out.txt OUT)
file(READ ${GOLDEN} EXP)
if(NOT OUT STREQUAL EXP)
  message(FATAL_ERROR "stdout mismatch")
endif()
