if(NOT DEFINED ILC)
  message(FATAL_ERROR "ILC not set")
endif()
if(NOT DEFINED SRC_DIR)
  message(FATAL_ERROR "SRC_DIR not set")
endif()
if(NOT DEFINED GOLDEN)
  message(FATAL_ERROR "GOLDEN not set")
endif()
execute_process(WORKING_DIRECTORY ${SRC_DIR}
                COMMAND ${ILC} front basic -run tests/e2e/BreakSrcExact.bas --break-src tests/e2e/BreakSrcExact.bas:2
                ERROR_FILE ${SRC_DIR}/out.txt RESULT_VARIABLE r)
if(NOT r EQUAL 10)
  message(FATAL_ERROR "expected breakpoint exit")
endif()
file(READ ${SRC_DIR}/out.txt OUT)
file(REMOVE ${SRC_DIR}/out.txt)
file(READ ${GOLDEN} EXP)
if(NOT OUT STREQUAL EXP)
  message(FATAL_ERROR "output mismatch")
endif()
