file(MAKE_DIRECTORY "${OUT}")
execute_process(COMMAND "${ILC}" -run "${HELLO}" OUTPUT_FILE "${OUT}/out1.txt" RESULT_VARIABLE R1)
if(NOT R1 EQUAL 0)
  message(FATAL_ERROR "hello_cond.il failed")
endif()
execute_process(COMMAND "${ILC}" -run "${SUM}" OUTPUT_FILE "${OUT}/out2.txt" RESULT_VARIABLE R2)
if(NOT R2 EQUAL 0)
  message(FATAL_ERROR "sum_1_to_10.il failed")
endif()
file(READ "${OUT}/out1.txt" OUT1)
file(READ "${OUT}/out2.txt" OUT2)
string(FIND "${OUT1}" "HELLO" POS)
if(POS EQUAL -1)
  message(FATAL_ERROR "HELLO not found")
endif()
string(FIND "${OUT1}" "READY" POS2)
if(POS2 EQUAL -1)
  message(FATAL_ERROR "READY not found")
endif()
string(REGEX MATCHALL "[0-9]+" NUMS1 "${OUT1}")
list(LENGTH NUMS1 COUNT1)
if(NOT COUNT1 EQUAL 2)
  message(FATAL_ERROR "expected two integers in hello output")
endif()
foreach(str "SUM 1..10" "55" "DONE")
  string(FIND "${OUT2}" "${str}" POS3)
  if(POS3 EQUAL -1)
    message(FATAL_ERROR "${str} not found")
  endif()
endforeach()
