execute_process(COMMAND ${ILC} front basic -emit-il ${SRC_DIR}/docs/examples/basic/ex1_hello_cond.bas
                OUTPUT_FILE basic.il RESULT_VARIABLE r1)
if(NOT r1 EQUAL 0)
  message(FATAL_ERROR "emit-il failed")
endif()
file(READ basic.il IL_OUT)
string(REGEX MATCH "HELLO" _il1 "${IL_OUT}")
if(NOT _il1)
  message(FATAL_ERROR "missing HELLO in IL output")
endif()

execute_process(COMMAND ${ILC} front basic -run ${SRC_DIR}/docs/examples/basic/ex1_hello_cond.bas
                OUTPUT_FILE run.txt RESULT_VARIABLE r2)
if(NOT r2 EQUAL 0)
  message(FATAL_ERROR "execution failed")
endif()
file(READ run.txt R1)
string(REGEX MATCH "HELLO" _m1 "${R1}")
if(NOT _m1)
  message(FATAL_ERROR "missing HELLO")
endif()
string(REGEX MATCH "READY" _m2 "${R1}")
if(NOT _m2)
  message(FATAL_ERROR "missing READY")
endif()
string(REGEX MATCHALL "[0-9]+" nums "${R1}")
list(LENGTH nums n)
if(NOT n EQUAL 2)
  message(FATAL_ERROR "expected two integers in output")
endif()
