if(NOT DEFINED ILC)
  message(FATAL_ERROR "ILC not set")
endif()
if(NOT DEFINED SRC_FILE)
  message(FATAL_ERROR "SRC_FILE not set")
endif()
if(NOT DEFINED GOLDEN)
  message(FATAL_ERROR "GOLDEN not set")
endif()
if(NOT DEFINED LINE)
  message(FATAL_ERROR "LINE not set")
endif()
if(NOT DEFINED ROOT)
  message(FATAL_ERROR "ROOT not set")
endif()
set(BREAK_FILE ${ROOT}/break.txt)
execute_process(COMMAND ${ILC} -run ${SRC_FILE} --break-src ${SRC_FILE}:${LINE}
                ERROR_FILE ${BREAK_FILE}
                RESULT_VARIABLE r
                WORKING_DIRECTORY ${ROOT})
if(NOT r EQUAL 10)
  message(FATAL_ERROR "expected breakpoint")
endif()
file(READ ${BREAK_FILE} OUT)
file(READ ${GOLDEN} EXP)
if(NOT OUT STREQUAL EXP)
  message(FATAL_ERROR "break output mismatch")
endif()

get_filename_component(BASENAME ${SRC_FILE} NAME)
set(BREAK_FILE2 ${ROOT}/break_base.txt)
execute_process(COMMAND ${ILC} -run ${SRC_FILE} --break-src ${BASENAME}:${LINE}
                ERROR_FILE ${BREAK_FILE2}
                RESULT_VARIABLE r
                WORKING_DIRECTORY ${ROOT})
if(NOT r EQUAL 10)
  message(FATAL_ERROR "expected breakpoint")
endif()
file(READ ${BREAK_FILE2} OUT)
if(NOT OUT STREQUAL EXP)
  message(FATAL_ERROR "break output mismatch (basename)")
endif()
