if(NOT DEFINED ILC)
  message(FATAL_ERROR "ILC not set")
endif()
if(NOT DEFINED BAS_FILE)
  message(FATAL_ERROR "BAS_FILE not set")
endif()
if(NOT DEFINED GOLDEN)
  message(FATAL_ERROR "GOLDEN not set")
endif()
execute_process(COMMAND ${ILC} front basic -run ${BAS_FILE} --break ${BAS_FILE}:2
                OUTPUT_FILE pre.out ERROR_FILE pre.err RESULT_VARIABLE r1)
if(NOT r1 EQUAL 10)
  message(FATAL_ERROR "expected breakpoint exit")
endif()
file(READ pre.err ERR)
string(FIND "${ERR}" "[BREAK]" pos)
if(pos EQUAL -1)
  message(FATAL_ERROR "missing break line")
endif()
file(READ pre.out OUT1)
string(FIND "${OUT1}" "2" pos2)
if(NOT pos2 EQUAL -1)
  message(FATAL_ERROR "second line executed before break")
endif()
set(SCRIPT "${CMAKE_CURRENT_BINARY_DIR}/script.txt")
file(WRITE ${SCRIPT} "continue\n")
execute_process(COMMAND ${ILC} front basic -run ${BAS_FILE} --break ${BAS_FILE}:2 --debug-cmds ${SCRIPT}
                OUTPUT_FILE out.txt RESULT_VARIABLE r2)
if(NOT r2 EQUAL 0)
  message(FATAL_ERROR "run with continue failed")
endif()
file(READ out.txt OUT2)
file(READ ${GOLDEN} EXP)
if(NOT OUT2 STREQUAL EXP)
  message(FATAL_ERROR "output mismatch")
endif()
