if(NOT DEFINED ILC)
  message(FATAL_ERROR "ILC not set")
endif()
if(NOT DEFINED BAS_FILE)
  message(FATAL_ERROR "BAS_FILE not set")
endif()
if(NOT DEFINED GOLDEN)
  message(FATAL_ERROR "GOLDEN not set")
endif()
set(DBG "${CMAKE_CURRENT_BINARY_DIR}/dbg.txt")
file(WRITE ${DBG} "continue\n")
execute_process(COMMAND ${ILC} front basic -run ${BAS_FILE} --break ${BAS_FILE}:2 --debug-cmds ${DBG}
                WORKING_DIRECTORY ${CMAKE_CURRENT_BINARY_DIR}
                OUTPUT_FILE out.txt ERROR_FILE err.txt RESULT_VARIABLE r)
if(NOT r EQUAL 0)
  message(FATAL_ERROR "execution failed")
endif()
file(READ err.txt ERR)
string(FIND "${ERR}" "[BREAK]" pos)
if(pos EQUAL -1)
  message(FATAL_ERROR "missing break")
endif()
file(READ out.txt OUT)
file(READ ${GOLDEN} EXP)
if(NOT OUT STREQUAL EXP)
  message(FATAL_ERROR "output mismatch")
endif()
