if(NOT DEFINED ILC)
  message(FATAL_ERROR "ILC not set")
endif()
if(NOT DEFINED SRC_DIR)
  message(FATAL_ERROR "SRC_DIR not set")
endif()
if(NOT DEFINED GOLDEN)
  message(FATAL_ERROR "GOLDEN not set")
endif()

set(BAS ${SRC_DIR}/examples/basic/break_src_line.bas)
set(SCRIPT break.cont)
file(WRITE ${SCRIPT} "continue\n")

execute_process(COMMAND ${ILC} front basic -run ${BAS} --break ${BAS}:2 --debug-cmds ${SCRIPT}
                OUTPUT_FILE out.txt ERROR_FILE err.txt RESULT_VARIABLE r)
if(NOT r EQUAL 0)
  message(FATAL_ERROR "execution failed")
endif()
 file(READ err.txt ERR)
 string(FIND "${ERR}" "[BREAK]" HAS_BREAK)
 if(HAS_BREAK EQUAL -1)
   message(FATAL_ERROR "missing break output")
 endif()
file(READ out.txt OUT)
file(READ ${GOLDEN} EXP)
if(NOT OUT STREQUAL EXP)
  message(FATAL_ERROR "stdout mismatch")
endif()
