if(NOT DEFINED ILC)
  message(FATAL_ERROR "ILC not set")
endif()
if(NOT DEFINED SRC_FILE)
  message(FATAL_ERROR "SRC_FILE not set")
endif()
if(NOT DEFINED GOLDEN)
  message(FATAL_ERROR "GOLDEN not set")
endif()
if(NOT DEFINED LINE)
  message(FATAL_ERROR "LINE not set")
endif()
if(NOT DEFINED ROOT)
  message(FATAL_ERROR "ROOT not set")
endif()
set(BREAK_FILE ${ROOT}/break.txt)
execute_process(COMMAND ${ILC} -run ${SRC_FILE} --break-src ${SRC_FILE}:${LINE}
                ERROR_FILE ${BREAK_FILE}
                RESULT_VARIABLE r
                WORKING_DIRECTORY ${ROOT})
if(NOT r EQUAL 10)
  message(FATAL_ERROR "expected breakpoint")
endif()
file(READ ${BREAK_FILE} OUT)
file(READ ${GOLDEN} EXP)
if(NOT OUT STREQUAL EXP)
  message(FATAL_ERROR "break output mismatch")
endif()

execute_process(COMMAND ${ILC} -run ${SRC_FILE} --break-src BreakSrcExact.bas:${LINE}
                ERROR_FILE ${BREAK_FILE}
                RESULT_VARIABLE r2
                WORKING_DIRECTORY ${ROOT})
if(NOT r2 EQUAL 10)
  message(FATAL_ERROR "expected breakpoint (basename)")
endif()
file(READ ${BREAK_FILE} OUT2)
if(NOT OUT2 STREQUAL EXP)
  message(FATAL_ERROR "break output mismatch (basename)")
endif()
