if(NOT DEFINED ILC)
  message(FATAL_ERROR "ILC not set")
endif()
if(NOT DEFINED SRC_DIR)
  message(FATAL_ERROR "SRC_DIR not set")
endif()
set(IL_FILE "${SRC_DIR}/tests/il/e2e/math_trigpow.il")
set(GOLDEN "${SRC_DIR}/tests/il/e2e/math_trigpow.out")
execute_process(
  COMMAND ${ILC} -run ${IL_FILE}
  OUTPUT_VARIABLE OUT
  OUTPUT_STRIP_TRAILING_WHITESPACE
  RESULT_VARIABLE r)
if(NOT r EQUAL 0)
  message(FATAL_ERROR "math_trigpow execution failed")
endif()
file(READ ${GOLDEN} EXP)
string(REPLACE "\\n" "\n" OUT "${OUT}")
string(REPLACE "\r\n" "\n" OUT "${OUT}")
string(REPLACE "\r\n" "\n" EXP "${EXP}")
string(STRIP "${OUT}" OUT)
string(STRIP "${EXP}" EXP)
if(NOT OUT STREQUAL EXP)
  message(FATAL_ERROR "stdout mismatch")
endif()
