execute_process(COMMAND ${ILC} -run ${SRC_DIR}/docs/examples/il/ex5_strings.il
                OUTPUT_FILE out.txt RESULT_VARIABLE r)
if(NOT r EQUAL 0)
  message(FATAL_ERROR "ex5_strings execution failed")
endif()
file(READ out.txt S)
string(REGEX MATCH "JOHN DOE" _m1 "${S}")
if(NOT _m1)
  message(FATAL_ERROR "missing JOHN DOE")
endif()
string(REGEX MATCH "\\\\n8\\\\n" _m2 "${S}")
if(NOT _m2)
  message(FATAL_ERROR "missing 8")
endif()
string(REGEX MATCH "\\\\nJ\\\\n" _m3 "${S}")
if(NOT _m3)
  message(FATAL_ERROR "missing J")
endif()
string(REGEX MATCH "1\\\\n$" _m4 "${S}")
if(NOT _m4)
  message(FATAL_ERROR "missing final 1")
endif()
