REM Test 2: Main -> FUNCTION -> Main (INTEGER)
DIM VALUE AS INTEGER
VALUE = 100

PRINT "=== Test 2: Main -> FUNCTION -> Main (INTEGER) ==="
PRINT "Main before FUNCTION: VALUE = " + STR$(VALUE)

FUNCTION GetDoubled() AS INTEGER
    PRINT "In FUNCTION: VALUE = " + STR$(VALUE)
    RETURN VALUE * 2
END FUNCTION

DIM result AS INTEGER
result = GetDoubled()
PRINT "FUNCTION returned: " + STR$(result)
PRINT "Main after FUNCTION: VALUE = " + STR$(VALUE)
PRINT ""

END
