PRINT "=== API Audit: Viper.GUI (All Classes) ==="
PRINT "NOTE: GUI requires windowed app. API surface documentation only."
PRINT ""
PRINT "--- App ---"
PRINT "New(title,w,h), Destroy(), ShouldClose, Poll(), Render(), Root, SetFont(font,size)"
PRINT "--- Font ---"
PRINT "Load(path), Destroy()"
PRINT "--- Widget (base) ---"
PRINT "Destroy(), SetVisible(v), SetEnabled(e), SetSize(w,h), SetFlex(f), AddChild(w), IsHovered, IsPressed, IsFocused, WasClicked, SetPosition(x,y)"
PRINT "--- Label ---"
PRINT "New(parent,text), SetText(s), SetFont(f,sz), SetColor(c)"
PRINT "--- Button ---"
PRINT "New(parent,text), SetText(s), SetFont(f,sz), SetStyle(s), WasClicked"
PRINT "--- TextInput ---"
PRINT "New(parent), SetText(s), Text, SetPlaceholder(s), SetFont(f,sz)"
PRINT "--- Checkbox ---"
PRINT "New(parent,text), SetChecked(v), IsChecked, SetText(s)"
PRINT "--- ScrollView ---"
PRINT "New(parent), SetScroll(x,y), SetContentSize(w,h)"
PRINT "--- TreeView ---"
PRINT "New(parent), AddNode(parent,text), RemoveNode(n), Clear(), Expand(n), Collapse(n), Select(n), SetFont(f,sz), GetSelected, WasSelectionChanged"
PRINT "--- TabBar ---"
PRINT "New(parent), AddTab(title,closable), RemoveTab(t), SetActive(t), GetActive, GetActiveIndex, WasChanged, TabCount, WasCloseClicked, GetCloseClickedIndex"
PRINT "--- SplitPane ---"
PRINT "New(parent,vertical), SetPosition(ratio), First, Second"
PRINT "--- CodeEditor ---"
PRINT "New(parent), SetText(s), Text, SetCursor(ln,col), ScrollToLine(n), LineCount, IsModified, ClearModified, SetFont(f,sz), CursorLine, CursorCol"
PRINT "--- Dropdown ---"
PRINT "New(parent), AddItem(s), RemoveItem(idx), Clear(), SetSelected(idx), Selected, SelectedText, SetPlaceholder(s)"
PRINT "--- Slider ---"
PRINT "New(parent,vertical), SetValue(v), Value, SetRange(min,max), SetStep(s)"
PRINT "--- ProgressBar ---"
PRINT "New(parent), SetValue(v), Value"
PRINT "--- ListBox ---"
PRINT "New(parent), AddItem(s), RemoveItem(item), Clear(), Select(item), Selected, Count, SelectedIndex, SelectIndex(idx), WasSelectionChanged"
PRINT "--- RadioGroup / RadioButton ---"
PRINT "RadioGroup.New(), RadioButton.New(parent,text,group), IsSelected, SetSelected(v)"
PRINT "--- Spinner ---"
PRINT "New(parent), SetValue(v), Value, SetRange(min,max), SetStep(s), SetDecimals(n)"
PRINT "--- Image ---"
PRINT "New(parent), SetPixels(px,w,h), Clear(), SetScaleMode(m), SetOpacity(o)"
PRINT "--- Theme ---"
PRINT "SetDark(), SetLight()"
PRINT "--- Layout ---"
PRINT "VBox.New(), HBox.New(), SetSpacing(s), SetPadding(p)"
PRINT "--- Clipboard ---"
PRINT "SetText(s), GetText(), HasText(), Clear()"
PRINT "--- Shortcuts ---"
PRINT "Register(id,keys,desc), Unregister(id), Clear(), IsEnabled(id), SetEnabled(id,v), GetGlobalEnabled, SetGlobalEnabled(v), WasTriggered(id), GetTriggered"
PRINT "--- Cursor ---"
PRINT "Set(type), Reset(), SetVisible(v)"
PRINT "--- MenuBar/Menu/MenuItem ---"
PRINT "MenuBar.New(parent), AddMenu(name); Menu.AddItem(name), AddSeparator(), AddSubmenu(name)"
PRINT "MenuItem.SetText(s), SetEnabled(v), IsEnabled, SetChecked(v), IsChecked, SetShortcut(s), WasClicked"
PRINT "--- ContextMenu ---"
PRINT "New(), AddItem(name), AddItemWithShortcut(name,keys), AddSeparator(), Show(x,y), Hide(), IsVisible, Clear()"
PRINT "--- StatusBar ---"
PRINT "New(parent), SetLeftText(s), SetCenterText(s), SetRightText(s), SetVisible(v), IsVisible, AddText(text,align)"
PRINT "--- Toolbar ---"
PRINT "New(parent), AddButton(icon,id), AddButtonWithText(icon,id,text), AddSeparator(), SetIconSize(sz), SetStyle(s), GetItemCount, SetVisible(v), IsVisible"
PRINT "--- Toast ---"
PRINT "Info(msg), Success(msg), Warning(msg), Error(msg), New(msg,type,duration), SetAction(text), WasActionClicked, WasDismissed, Dismiss(), SetPosition(pos), SetMaxVisible(n), DismissAll()"
PRINT "--- Breadcrumb ---"
PRINT "New(parent), SetPath(path,sep), SetItems(json), AddItem(text,data), Clear(), WasItemClicked, GetClickedIndex, GetClickedData, SetSeparator(s), SetMaxItems(n)"
PRINT "--- Minimap ---"
PRINT "New(parent), BindEditor(ed), UnbindEditor(), SetWidth(w), GetWidth, SetScale(s), SetShowSlider(v), AddMarker(line,type,color), RemoveMarkers(type), ClearMarkers()"
PRINT "--- MessageBox ---"
PRINT "Info(title,msg), Warning(title,msg), Error(title,msg), Question(title,msg), Confirm(title,msg)"
PRINT "--- FileDialog ---"
PRINT "Open(title,dir,filter), OpenMultiple(title,dir,filter), Save(title,dir,filter,default), SelectFolder(title,dir)"
PRINT "--- FindBar ---"
PRINT "New(editor), SetFindText(s), GetFindText, SetReplaceText(s), GetReplaceText, SetCaseSensitive(v), SetWholeWord(v), SetRegex(v), FindNext, FindPrev, Replace, ReplaceAll, GetMatchCount, GetCurrentMatch, Focus"
PRINT "--- CommandPalette ---"
PRINT "New(parent), AddCommand(id,name,desc), AddCommandWithShortcut(id,name,desc,keys), RemoveCommand(id), Clear(), Show(), Hide(), IsVisible, SetPlaceholder(s), GetSelected, WasSelected"
PRINT "--- Tooltip ---"
PRINT "Show(text,x,y), ShowRich(title,body,x,y), Hide(), SetDelay(ms), Widget.SetTooltip(text), Widget.SetTooltipRich(title,body), Widget.ClearTooltip"
PRINT "--- Drag and Drop ---"
PRINT "Widget.SetDraggable(v), SetDragData(type,data), IsBeingDragged, SetDropTarget(v), SetAcceptedDropTypes(types), IsDragOver, WasDropped, GetDropType, GetDropData"
PRINT ""
PRINT "=== GUI Audit Complete (API surface only) ==="
END
