PRINT "=== API Audit: Viper.Input (All Classes) ==="
PRINT "NOTE: Input classes require a window/event loop. API surface documentation only."
PRINT ""
PRINT "--- Keyboard ---"
PRINT "IsKeyDown(key), IsKeyUp(key), WasKeyPressed(key), WasKeyReleased(key)"
PRINT "GetModifiers(), IsShiftDown(), IsCtrlDown(), IsAltDown()"
PRINT ""
PRINT "--- Mouse ---"
PRINT "get_X, get_Y, get_DeltaX, get_DeltaY"
PRINT "IsButtonDown(btn), WasButtonPressed(btn), WasButtonReleased(btn)"
PRINT "get_ScrollX, get_ScrollY, SetCursorVisible(v), SetCursorLocked(v)"
PRINT ""
PRINT "--- Pad (Gamepad) ---"
PRINT "IsConnected(idx), GetAxis(idx,axis), IsButtonDown(idx,btn)"
PRINT "WasButtonPressed(idx,btn), WasButtonReleased(idx,btn)"
PRINT "get_ConnectedCount, GetName(idx), SetDeadzone(idx,dz)"
PRINT "GetLeftStickX(idx), GetLeftStickY(idx), GetRightStickX(idx), GetRightStickY(idx)"
PRINT "GetLeftTrigger(idx), GetRightTrigger(idx)"
PRINT ""
PRINT "--- Action ---"
PRINT "New(name), BindKey(key), BindMouseButton(btn), BindPadButton(padIdx,btn), BindPadAxis(padIdx,axis,threshold)"
PRINT "IsActive(), WasActivated(), WasDeactivated(), GetValue()"
PRINT "Unbind(), SetDeadzone(dz)"
PRINT ""
PRINT "--- Manager ---"
PRINT "New(), AddAction(action), GetAction(name), RemoveAction(name), Update()"
PRINT "Clear(), get_ActionCount"
PRINT ""
PRINT "--- KeyChord ---"
PRINT "New(key1,key2), NewTriple(key1,key2,key3), IsActive(), WasActivated()"
PRINT "SetKeys(key1,key2), SetKeysTriple(key1,key2,key3)"
PRINT ""
PRINT "=== Input Audit Complete (API surface only) ==="
END
