10 DIM result AS BOOLEAN
20 LET result = TRUE
30 IF result THEN PRINT 1 ELSE PRINT 0
40 LET result = FALSE
50 IF result THEN PRINT 1 ELSE PRINT 0
60 IF NOT TRUE THEN PRINT 1 ELSE PRINT 0
70 IF NOT FALSE THEN PRINT 1 ELSE PRINT 0
80 IF TRUE ANDALSO TRUE THEN PRINT 1 ELSE PRINT 0
90 IF TRUE ANDALSO FALSE THEN PRINT 1 ELSE PRINT 0
100 IF FALSE ANDALSO TRUE THEN PRINT 1 ELSE PRINT 0
110 IF FALSE ANDALSO FALSE THEN PRINT 1 ELSE PRINT 0
120 IF TRUE ORELSE FALSE THEN PRINT 1 ELSE PRINT 0
130 IF TRUE ORELSE TRUE THEN PRINT 1 ELSE PRINT 0
140 IF FALSE ORELSE FALSE THEN PRINT 1 ELSE PRINT 0
150 IF FALSE ORELSE TRUE THEN PRINT 1 ELSE PRINT 0
160 END
