' Test 04: ANSI color codes
DIM ESC AS STRING
ESC = CHR(27)

DIM RED AS STRING
DIM GREEN AS STRING
DIM YELLOW AS STRING
DIM BLUE AS STRING
DIM RESET AS STRING

RED = ESC + "[31m"
GREEN = ESC + "[32m"
YELLOW = ESC + "[33m"
BLUE = ESC + "[34m"
RESET = ESC + "[0m"

PRINT RED + "Red text" + RESET
PRINT GREEN + "Green text" + RESET
PRINT YELLOW + "Yellow text" + RESET
PRINT BLUE + "Blue text" + RESET
END
