if (NOT DEFINED ILC)
    message(FATAL_ERROR "ILC not set")
endif ()
if (NOT DEFINED IL_FILE)
    message(FATAL_ERROR "IL_FILE not set")
endif ()
execute_process(COMMAND ${ILC} il-opt ${IL_FILE} -o ${IL_FILE}.opt --mem2reg-stats OUTPUT_VARIABLE out RESULT_VARIABLE r)
if (NOT r EQUAL 0)
    message(FATAL_ERROR "il-opt failed")
endif ()
string(REGEX MATCH "mem2reg: promoted 2, removed loads 2, removed stores 2" m "${out}")
if (NOT m)
    message(FATAL_ERROR "stats mismatch: ${out}")
endif ()
