if (NOT DEFINED ILC)
    message(FATAL_ERROR "ILC not set")
endif ()
if (NOT DEFINED BAS_FILE)
    message(FATAL_ERROR "BAS_FILE not set")
endif ()
# Use input filename to create unique output to avoid parallel test races
get_filename_component(BAS_NAME ${BAS_FILE} NAME_WE)
set(IL_FILE "${CMAKE_CURRENT_BINARY_DIR}/${BAS_NAME}_compile_only.il")
execute_process(COMMAND ${ILC} front basic -emit-il ${BAS_FILE} OUTPUT_FILE ${IL_FILE} RESULT_VARIABLE r1)
if (NOT r1 EQUAL 0)
    message(FATAL_ERROR "emit-il failed")
endif ()
# Verify IL well-formedness using il-verify next to ilc
set(IL_VERIFY ${ILC})
# Handle both Unix and Windows paths (CMake uses forward slashes even on Windows)
string(REPLACE "/tools/viper/viper" "/tools/il-verify/il-verify" IL_VERIFY ${IL_VERIFY})
string(REPLACE "/tools/ilc/Debug/ilc.exe" "/tools/il-verify/Debug/il-verify.exe" IL_VERIFY ${IL_VERIFY})
string(REPLACE "/tools/ilc/Release/ilc.exe" "/tools/il-verify/Release/il-verify.exe" IL_VERIFY ${IL_VERIFY})
# Handle Windows viper.exe paths with config subdirectories
string(REPLACE "/tools/viper/Debug/viper.exe" "/tools/il-verify/Debug/il-verify.exe" IL_VERIFY ${IL_VERIFY})
string(REPLACE "/tools/viper/Release/viper.exe" "/tools/il-verify/Release/il-verify.exe" IL_VERIFY ${IL_VERIFY})
execute_process(COMMAND ${IL_VERIFY} ${IL_FILE} RESULT_VARIABLE r2)
if (NOT r2 EQUAL 0)
    message(FATAL_ERROR "il-verify failed")
endif ()
