# File: tests/e2e/test_simplifycfg_smoke.cmake
# Purpose: Ensure simplify-cfg preserves behavior while shrinking trivial blocks.
# Key invariants: Optimized IL emits identical stdout and has fewer blocks/instructions.
# Ownership/Lifetime: Invoked by CTest.
# Links: docs/codemap.md

if (NOT DEFINED ILC)
    message(FATAL_ERROR "ILC not set")
endif ()
if (NOT DEFINED IL_FILE)
    message(FATAL_ERROR "IL_FILE not set")
endif ()
if (NOT DEFINED GOLDEN)
    message(FATAL_ERROR "GOLDEN not set")
endif ()

set(OPT_FILE "${CMAKE_CURRENT_BINARY_DIR}/simplifycfg_smoke.opt.il")
execute_process(COMMAND ${ILC} -run ${IL_FILE} OUTPUT_VARIABLE before RESULT_VARIABLE r1)
if (NOT r1 EQUAL 0)
    message(FATAL_ERROR "run before failed")
endif ()
execute_process(COMMAND ${ILC} il-opt ${IL_FILE} -o ${OPT_FILE} --passes simplify-cfg RESULT_VARIABLE r2)
if (NOT r2 EQUAL 0)
    message(FATAL_ERROR "il-opt failed")
endif ()
execute_process(COMMAND ${ILC} -run ${OPT_FILE} OUTPUT_VARIABLE after RESULT_VARIABLE r3)
if (NOT r3 EQUAL 0)
    message(FATAL_ERROR "run after failed")
endif ()

file(READ ${GOLDEN} golden)
if (NOT before STREQUAL golden)
    message(FATAL_ERROR "unexpected stdout before optimization")
endif ()
if (NOT after STREQUAL golden)
    message(FATAL_ERROR "unexpected stdout after optimization")
endif ()

function(simplifycfg_count_ir FILE_OUT BLOCK_VAR INST_VAR)
    file(STRINGS ${FILE_OUT} _lines)
    set(_block_count 0)
    set(_inst_count 0)
    foreach (_line IN LISTS _lines)
        string(STRIP "${_line}" _trimmed)
        if (_trimmed MATCHES "^[A-Za-z0-9_.]+:")
            math(EXPR _block_count "${_block_count} + 1")
        endif ()
        if (_line MATCHES "^  [^ ].*")
            math(EXPR _inst_count "${_inst_count} + 1")
        endif ()
    endforeach ()
    set(${BLOCK_VAR} ${_block_count} PARENT_SCOPE)
    set(${INST_VAR} ${_inst_count} PARENT_SCOPE)
endfunction()

simplifycfg_count_ir(${IL_FILE} before_block_count before_inst_count)
simplifycfg_count_ir(${OPT_FILE} after_block_count after_inst_count)
if (NOT after_block_count LESS before_block_count)
    message(FATAL_ERROR "expected fewer blocks after simplify-cfg: before=${before_block_count}, after=${after_block_count}")
endif ()
if (NOT after_inst_count LESS before_inst_count)
    message(FATAL_ERROR "expected fewer instructions after simplify-cfg: before=${before_inst_count}, after=${after_inst_count}")
endif ()
