if (NOT DEFINED ILC)
    message(FATAL_ERROR "ILC not set")
endif ()
if (NOT DEFINED BAS_FILE)
    message(FATAL_ERROR "BAS_FILE not set")
endif ()
set(IL_FILE "${CMAKE_CURRENT_BINARY_DIR}/mem2reg.il")
execute_process(COMMAND ${ILC} front basic -emit-il ${BAS_FILE} OUTPUT_FILE ${IL_FILE} RESULT_VARIABLE r1)
if (NOT r1 EQUAL 0)
    message(FATAL_ERROR "emit-il failed")
endif ()
execute_process(COMMAND ${ILC} -run ${IL_FILE} OUTPUT_VARIABLE before RESULT_VARIABLE r2)
if (NOT r2 EQUAL 0)
    message(FATAL_ERROR "run before failed")
endif ()
set(OPT_FILE "${CMAKE_CURRENT_BINARY_DIR}/mem2reg.opt.il")
execute_process(COMMAND ${ILC} il-opt ${IL_FILE} -o ${OPT_FILE} --passes mem2reg RESULT_VARIABLE r3)
if (NOT r3 EQUAL 0)
    message(FATAL_ERROR "il-opt failed")
endif ()
execute_process(COMMAND ${ILC} -run ${OPT_FILE} OUTPUT_VARIABLE after RESULT_VARIABLE r4)
if (NOT r4 EQUAL 0)
    message(FATAL_ERROR "run after failed")
endif ()
if (NOT before STREQUAL after)
    message(FATAL_ERROR "stdout mismatch")
endif ()
