if (NOT DEFINED ILC)
    message(FATAL_ERROR "ILC not set")
endif ()
if (NOT DEFINED BAS_FILE)
    message(FATAL_ERROR "BAS_FILE not set")
endif ()
set(IL_FILE "${CMAKE_CURRENT_BINARY_DIR}/compile_only.il")
execute_process(COMMAND ${ILC} front basic -emit-il ${BAS_FILE} OUTPUT_FILE ${IL_FILE} RESULT_VARIABLE r1)
if (NOT r1 EQUAL 0)
    message(FATAL_ERROR "emit-il failed")
endif ()
# Verify IL well-formedness using il-verify next to ilc
set(IL_VERIFY ${ILC})
string(REPLACE "/tools/ilc/ilc" "/tools/il-verify/il-verify" IL_VERIFY ${IL_VERIFY})
execute_process(COMMAND ${IL_VERIFY} ${IL_FILE} RESULT_VARIABLE r2)
if (NOT r2 EQUAL 0)
    message(FATAL_ERROR "il-verify failed")
endif ()
