FUNCTION F#(X#)
RETURN X#
END FUNCTION
FUNCTION ID$(S$)
RETURN S$
END FUNCTION
FUNCTION FIRST#(N)
IF N <= 0 THEN RETURN 0#
RETURN SECOND#(N)
END FUNCTION
FUNCTION SECOND#(N#)
IF N# <= 0 THEN RETURN 0#
RETURN FIRST#(N# - 1)
END FUNCTION
10 PRINT F#(1)
20 PRINT ID$("HI")
30 PRINT FIRST#(2)
40 END
