PRINT "=== API Audit: Viper.Sound (All Classes) ==="
PRINT "NOTE: Sound classes require audio hardware. API surface documentation only."
PRINT ""
PRINT "--- Audio ---"
PRINT "Init(), Shutdown(), SetMasterVolume(v), get_MasterVolume"
PRINT "SetListenerPosition(x,y), Pause(), Resume(), get_IsPaused"
PRINT ""
PRINT "--- Sound ---"
PRINT "Load(path), Destroy(), Play(), PlayLooped(loops)"
PRINT "Stop(), Pause(), Resume(), get_IsPlaying, get_IsPaused"
PRINT "SetVolume(v), get_Volume, SetPan(p), get_Pan"
PRINT "SetPitch(p), get_Pitch, SetPosition(x,y)"
PRINT ""
PRINT "--- Voice ---"
PRINT "Play(sound), PlayLooped(sound,loops), Stop(), Pause(), Resume()"
PRINT "get_IsPlaying, get_IsPaused, SetVolume(v), get_Volume"
PRINT "SetPan(p), get_Pan, SetPitch(p), get_Pitch"
PRINT "SetPosition(x,y), SetLooping(v)"
PRINT ""
PRINT "--- Music ---"
PRINT "Load(path), Destroy(), Play(), PlayLooped()"
PRINT "Stop(), Pause(), Resume(), get_IsPlaying, get_IsPaused"
PRINT "SetVolume(v), get_Volume, FadeIn(ms), FadeOut(ms)"
PRINT "get_Duration, get_Position, Seek(ms)"
PRINT ""
PRINT "--- Playlist ---"
PRINT "New(), Destroy(), Add(music), Remove(idx), Clear()"
PRINT "Play(), Stop(), Pause(), Resume(), Next(), Previous()"
PRINT "get_IsPlaying, get_IsPaused, get_CurrentIndex, get_Count"
PRINT "SetShuffle(v), get_Shuffle, SetLoop(v), get_Loop"
PRINT "SetVolume(v), get_Volume"
PRINT ""
PRINT "=== Sound Audit Complete (API surface only) ==="
END
