//===----------------------------------------------------------------------===//
//
// Part of the Viper project, under the GNU GPL v3.
// See LICENSE for license information.
//
//===----------------------------------------------------------------------===//
//
// File: src/runtime/graphics/fonts/embedded_font.h
// Purpose: Extern declarations for the embedded JetBrains Mono Regular font.
//
// The font data in embedded_font.c is auto-generated by
// scripts/embed_font.py from JetBrainsMono-Regular.ttf.
//
// JetBrains Mono is licensed under the SIL Open Font License 1.1.
// See https://www.jetbrains.com/lp/mono/ for details.
//
//===----------------------------------------------------------------------===//
#pragma once

/// @brief Raw TTF bytes for the embedded JetBrains Mono Regular font.
extern const unsigned char vg_embedded_font_data[];

/// @brief Size of vg_embedded_font_data in bytes.
extern const unsigned int vg_embedded_font_size;
