//===----------------------------------------------------------------------===//
//
// File: src/runtime/graphics/fonts/embedded_font.h
// Purpose: Extern declarations for the embedded JetBrains Mono Regular font stored as raw TTF bytes
// in embedded_font.c, auto-generated by scripts/embed_font.py.
//
// Key invariants:
//   - Font data is the complete TTF file embedded as a byte array.
//   - JetBrains Mono is licensed under the SIL Open Font License 1.1.
//   - The array length is provided by embedded_font_size.
//   - The data pointer is read-only; callers must not modify it.
//
// Ownership/Lifetime:
//   - The embedded font data is a global constant; no allocation or lifetime management.
//   - Callers borrow the pointer; they must not free it.
//
// Links: src/runtime/graphics/fonts/embedded_font.c (generated data)
//
//===----------------------------------------------------------------------===//
#pragma once

/// @brief Raw TTF bytes for the embedded JetBrains Mono Regular font.
extern const unsigned char vg_embedded_font_data[];

/// @brief Size of vg_embedded_font_data in bytes.
extern const unsigned int vg_embedded_font_size;
