if (NOT DEFINED IL_VERIFY)
    message(FATAL_ERROR "IL_VERIFY not set")
endif ()
if (NOT DEFINED FILE)
    message(FATAL_ERROR "FILE not set")
endif ()
if (NOT DEFINED EXPECT)
    message(FATAL_ERROR "EXPECT not set")
endif ()
execute_process(COMMAND ${IL_VERIFY} ${FILE} RESULT_VARIABLE res OUTPUT_VARIABLE out ERROR_VARIABLE out)
if (res EQUAL 0)
    message(FATAL_ERROR "expected non-zero exit")
endif ()
if (NOT out MATCHES "${EXPECT}")
    message(FATAL_ERROR "expected message not found: ${EXPECT}\n${out}")
endif ()
