# File: tests/basic/semantics/check_diag.cmake
# Purpose: Run BASIC frontend and compare diagnostics with expected output.
if (NOT DEFINED ILC)
    message(FATAL_ERROR "ILC not set")
endif ()
if (NOT DEFINED BAS_FILE)
    message(FATAL_ERROR "BAS_FILE not set")
endif ()
if (NOT DEFINED DIAG_FILE)
    message(FATAL_ERROR "DIAG_FILE not set")
endif ()
if (NOT DEFINED EXPECT_STATUS)
    set(EXPECT_STATUS 0)
endif ()
if (NOT DEFINED SOURCE_ROOT)
    set(SOURCE_ROOT "")
endif ()
file(READ ${DIAG_FILE} EXPECT_DIAG)
string(REPLACE "\r\n" "\n" EXPECT_DIAG "${EXPECT_DIAG}")
string(REGEX REPLACE "\n+$" "" EXPECT_DIAG "${EXPECT_DIAG}")
if (SOURCE_ROOT)
    file(RELATIVE_PATH BAS_EXPECT_PATH ${SOURCE_ROOT} ${BAS_FILE})
else ()
    set(BAS_EXPECT_PATH ${BAS_FILE})
endif ()
string(REPLACE "${BAS_FILE}" "${BAS_EXPECT_PATH}" EXPECT_DIAG "${EXPECT_DIAG}")
execute_process(
        COMMAND ${ILC} front basic -emit-il ${BAS_FILE}
        RESULT_VARIABLE RES
        OUTPUT_VARIABLE OUT
        ERROR_VARIABLE ERR
)
if (NOT RES EQUAL EXPECT_STATUS)
    message(FATAL_ERROR "unexpected exit status: expected ${EXPECT_STATUS}, got ${RES}. stderr: ${ERR}")
endif ()
string(REPLACE "\r\n" "\n" ERR "${ERR}")
string(REGEX REPLACE "\n+$" "" ERR "${ERR}")
string(REPLACE "${BAS_FILE}" "${BAS_EXPECT_PATH}" ERR "${ERR}")
if (NOT ERR STREQUAL EXPECT_DIAG)
    message(FATAL_ERROR "diagnostics mismatch\nexpected: '${EXPECT_DIAG}'\nactual: '${ERR}'")
endif ()
