if (NOT DEFINED ILC)
    message(FATAL_ERROR "ILC not set")
endif ()
if (NOT DEFINED IL_FILE)
    message(FATAL_ERROR "IL_FILE not set")
endif ()
if (NOT DEFINED EXPECT)
    message(FATAL_ERROR "EXPECT not set")
endif ()
execute_process(COMMAND ${ILC} -run ${IL_FILE} RESULT_VARIABLE res OUTPUT_VARIABLE out ERROR_VARIABLE out)
if (res EQUAL 0)
    message(FATAL_ERROR "expected non-zero exit")
endif ()
if (NOT out MATCHES "${EXPECT}")
    message(FATAL_ERROR "expected message not found: ${EXPECT}\n${out}")
endif ()
