' constants.bas - Monopoly game constants and enums
' Color and space type definitions

' Terminal colors
CONST CLR_BLACK AS INTEGER = 0
CONST CLR_RED AS INTEGER = 1
CONST CLR_GREEN AS INTEGER = 2
CONST CLR_YELLOW AS INTEGER = 3
CONST CLR_BLUE AS INTEGER = 4
CONST CLR_MAGENTA AS INTEGER = 5
CONST CLR_CYAN AS INTEGER = 6
CONST CLR_WHITE AS INTEGER = 7
CONST CLR_GRAY AS INTEGER = 8
CONST CLR_BRIGHT_RED AS INTEGER = 9
CONST CLR_BRIGHT_GREEN AS INTEGER = 10
CONST CLR_BRIGHT_YELLOW AS INTEGER = 11
CONST CLR_BRIGHT_BLUE AS INTEGER = 12
CONST CLR_BRIGHT_MAGENTA AS INTEGER = 13
CONST CLR_BRIGHT_CYAN AS INTEGER = 14
CONST CLR_BRIGHT_WHITE AS INTEGER = 15

' Property group colors (for display)
CONST GRP_BROWN AS INTEGER = 1
CONST GRP_LIGHTBLUE AS INTEGER = 2
CONST GRP_PINK AS INTEGER = 3
CONST GRP_ORANGE AS INTEGER = 4
CONST GRP_RED AS INTEGER = 5
CONST GRP_YELLOW AS INTEGER = 6
CONST GRP_GREEN AS INTEGER = 7
CONST GRP_DARKBLUE AS INTEGER = 8
CONST GRP_RAILROAD AS INTEGER = 9
CONST GRP_UTILITY AS INTEGER = 10

' Space types
CONST SPACE_GO AS INTEGER = 0
CONST SPACE_PROPERTY AS INTEGER = 1
CONST SPACE_RAILROAD AS INTEGER = 2
CONST SPACE_UTILITY AS INTEGER = 3
CONST SPACE_CHANCE AS INTEGER = 4
CONST SPACE_CHEST AS INTEGER = 5
CONST SPACE_TAX AS INTEGER = 6
CONST SPACE_JAIL AS INTEGER = 7
CONST SPACE_FREEPARKING AS INTEGER = 8
CONST SPACE_GOTOJAIL AS INTEGER = 9

' Card action types
CONST CARD_MOVE_TO AS INTEGER = 1
CONST CARD_MOVE_BACK AS INTEGER = 2
CONST CARD_COLLECT AS INTEGER = 3
CONST CARD_PAY AS INTEGER = 4
CONST CARD_PAY_EACH AS INTEGER = 5
CONST CARD_COLLECT_EACH AS INTEGER = 6
CONST CARD_REPAIRS AS INTEGER = 7
CONST CARD_JAIL AS INTEGER = 8
CONST CARD_JAIL_FREE AS INTEGER = 9
CONST CARD_NEAREST_RR AS INTEGER = 10
CONST CARD_NEAREST_UTIL AS INTEGER = 11

' AI Strategy types
CONST STRATEGY_AGGRESSIVE AS INTEGER = 1
CONST STRATEGY_CONSERVATIVE AS INTEGER = 2
CONST STRATEGY_BALANCED AS INTEGER = 3

' Player token colors
CONST TOKEN_ORANGE AS INTEGER = 3
CONST TOKEN_GREEN AS INTEGER = 2
CONST TOKEN_RED AS INTEGER = 1
CONST TOKEN_PURPLE AS INTEGER = 5

' Game constants
CONST STARTING_MONEY AS INTEGER = 1500
CONST GO_SALARY AS INTEGER = 200
CONST JAIL_POSITION AS INTEGER = 10
CONST GOTOJAIL_POSITION AS INTEGER = 30
CONST TOTAL_HOUSES AS INTEGER = 32
CONST TOTAL_HOTELS AS INTEGER = 12
CONST JAIL_FINE AS INTEGER = 50
CONST LUXURY_TAX AS INTEGER = 100
CONST INCOME_TAX AS INTEGER = 200
CONST MAX_JAIL_TURNS AS INTEGER = 3

' Board positions for special spaces
CONST POS_GO AS INTEGER = 0
CONST POS_JAIL AS INTEGER = 10
CONST POS_FREE_PARKING AS INTEGER = 20
CONST POS_GO_TO_JAIL AS INTEGER = 30

