#!/usr/bin/env python3
"""Convert a TTF/TTC file to a C source array for compile-time embedding.

Usage:
    python3 scripts/embed_font.py <font.ttf> > src/runtime/graphics/fonts/embedded_font.c

Re-run this script whenever the source font file is replaced.
The output is committed to the repository alongside the .ttf source.
"""
import sys


def main():
    if len(sys.argv) != 2:
        print(f"Usage: {sys.argv[0]} <font.ttf>", file=sys.stderr)
        sys.exit(1)
    path = sys.argv[1]
    with open(path, "rb") as f:
        data = f.read()
    import os
    font_name = os.path.basename(path)
    print("// Auto-generated by scripts/embed_font.py — do not edit manually.")
    print(f"// Source: {font_name}")
    print("//")
    print("// JetBrains Mono is licensed under the SIL Open Font License 1.1.")
    print("// See https://www.jetbrains.com/lp/mono/ for details.")
    print('#include "embedded_font.h"')
    print(f"const unsigned int  vg_embedded_font_size = {len(data)}u;")
    print("const unsigned char vg_embedded_font_data[] = {")
    for i in range(0, len(data), 16):
        chunk = data[i : i + 16]
        row = ", ".join(f"0x{b:02x}" for b in chunk)
        print(f"    {row},")
    print("};")


if __name__ == "__main__":
    main()
