//===----------------------------------------------------------------------===//
//
// Part of the Viper project, under the GNU GPL v3.
// See LICENSE for license information.
//
//===----------------------------------------------------------------------===//
//
// File: codegen/common/linker/DeadStripPass.cpp
// Purpose: Mark-and-sweep dead section stripping for the native linker.
//          Follows relocations to transitively mark live sections, then
//          clears data from unreachable sections so they occupy zero bytes.
// Key invariants:
    //   - Entry point, synthetic helpers, TLS, and init/runtime metadata are roots
    //   - Archive-extracted sections are live only if reachable
    //   - ObjC metadata, TLS, and init/fini sections are always roots
    //   - Liveness propagates through relocation symbol references
// Links: codegen/common/linker/DeadStripPass.hpp
//
//===----------------------------------------------------------------------===//

#include "codegen/common/linker/DeadStripPass.hpp"

#include "codegen/common/linker/LinkTypes.hpp"
#include "codegen/common/linker/NameMangling.hpp"
#include "codegen/common/linker/ObjFileReader.hpp"

#include <queue>
#include <unordered_set>

namespace viper::codegen::linker {

/// Encode (objIndex, secIndex) into a single key for the worklist.
static uint64_t makeKey(size_t objIdx, size_t secIdx) {
    return (static_cast<uint64_t>(objIdx) << 32) | static_cast<uint64_t>(secIdx);
}

/// Check if a section name indicates it must always be kept.
static bool isAlwaysLiveSection(const std::string &name) {
    // ObjC metadata — runtime discovers classes, selectors, protocols by section name.
    if (name.find("__objc_") != std::string::npos)
        return true;
    if (name.find("objc_") != std::string::npos)
        return true;

    // Mach-O init/fini function pointer sections.
    if (name.find("__mod_init_func") != std::string::npos)
        return true;
    if (name.find("__mod_term_func") != std::string::npos)
        return true;

    // ELF init/fini.
    if (name == ".init_array" || name == ".fini_array")
        return true;
    if (name == ".init" || name == ".fini")
        return true;

    // COFF CRT init/term tables. Keep every .CRT$* contribution alive so
    // sentinel ranges like __xi_a..__xi_z and __xc_a..__xc_z still bracket
    // the actual initializer callbacks after archive extraction.
    if (name.rfind(".CRT$", 0) == 0)
        return true;

    return false;
}

static bool isWindowsUnwindSection(const std::string &name) {
    return name.rfind(".pdata", 0) == 0 || name.rfind(".xdata", 0) == 0;
}

void deadStrip(std::vector<ObjFile> &allObjects,
               size_t userObjCount,
               const std::unordered_map<std::string, GlobalSymEntry> &globalSyms,
               const std::string &entrySymbol,
               std::ostream &err) {
    // Set of live (objIdx, secIdx) pairs.
    std::unordered_set<uint64_t> live;
    std::queue<uint64_t> worklist;

    auto markLive = [&](size_t objIdx, size_t secIdx) {
        uint64_t key = makeKey(objIdx, secIdx);
        if (live.insert(key).second)
            worklist.push(key);
    };

    // Phase 1: Identify roots.

    // Stub objects (generated by the linker) are always live.
    // They appear after archive extracts. Identify by name prefix.
    for (size_t oi = userObjCount; oi < allObjects.size(); ++oi) {
        const auto &obj = allObjects[oi];
        if (obj.name.size() > 0 && obj.name[0] == '<') {
            // Synthetic objects like <dyld-stubs>, <objc-stubs>
            for (size_t si = 1; si < obj.sections.size(); ++si)
                markLive(oi, si);
        }
    }

    // Entry point section is a root.
    {
        auto it = findWithMachoFallback(globalSyms, entrySymbol);
        if (it != globalSyms.end() && it->second.secIndex > 0)
            markLive(it->second.objIndex, it->second.secIndex);
    }

    // Always-live sections (ObjC, TLS, init/fini) across all input objects.
    for (size_t oi = 0; oi < allObjects.size(); ++oi) {
        const auto &obj = allObjects[oi];
        for (size_t si = 1; si < obj.sections.size(); ++si) {
            const auto &sec = obj.sections[si];
            if (sec.tls || isAlwaysLiveSection(sec.name))
                markLive(oi, si);
        }
    }

    // Phase 2: Mark — follow relocations transitively.
    // Build a quick lookup: symbol name → (objIdx, secIdx) for defined symbols.
    // We reuse globalSyms for global/weak symbols and handle locals per-object.

    while (!worklist.empty()) {
        uint64_t key = worklist.front();
        worklist.pop();

        size_t oi = static_cast<size_t>(key >> 32);
        size_t si = static_cast<size_t>(key & 0xFFFFFFFF);

        if (oi >= allObjects.size())
            continue;
        const auto &obj = allObjects[oi];
        if (si >= obj.sections.size())
            continue;
        const auto &sec = obj.sections[si];

        // Windows x64 unwind tables are reverse-referenced: .pdata points at
        // code labels, and .xdata is then pulled in from .pdata. When a live
        // code section is visited, mark sibling unwind sections whose
        // relocations target that section.
        if (obj.format == ObjFileFormat::COFF && sec.executable) {
            for (size_t otherSi = 1; otherSi < obj.sections.size(); ++otherSi) {
                if (otherSi == si)
                    continue;
                const auto &other = obj.sections[otherSi];
                if (!isWindowsUnwindSection(other.name))
                    continue;
                for (const auto &rel : other.relocs) {
                    if (rel.symIndex >= obj.symbols.size())
                        continue;
                    const auto &targetSym = obj.symbols[rel.symIndex];
                    if (targetSym.sectionIndex == si) {
                        markLive(oi, otherSi);
                        break;
                    }
                    if (!targetSym.name.empty()) {
                        auto git = globalSyms.find(targetSym.name);
                        if (git != globalSyms.end() && git->second.objIndex == oi &&
                            git->second.secIndex == si) {
                            markLive(oi, otherSi);
                            break;
                        }
                    }
                }
            }
        }

        // Follow each relocation to its target symbol's section.
        for (const auto &rel : sec.relocs) {
            if (rel.symIndex == 0 || rel.symIndex >= obj.symbols.size())
                continue;

            const auto &sym = obj.symbols[rel.symIndex];

            // Local symbols: resolve within same object.
            if (sym.sectionIndex > 0 && sym.sectionIndex < obj.sections.size()) {
                markLive(oi, sym.sectionIndex);
            }

            // Global/weak symbols: look up in global table.
            if (!sym.name.empty()) {
                auto git = globalSyms.find(sym.name);
                if (git != globalSyms.end() && git->second.secIndex > 0)
                    markLive(git->second.objIndex, git->second.secIndex);
            }
        }
    }

    // Phase 3: Sweep — clear data from dead sections.
    size_t strippedSections = 0;
    size_t strippedBytes = 0;
    for (size_t oi = 0; oi < allObjects.size(); ++oi) {
        auto &obj = allObjects[oi];
        // Skip synthetic objects (already marked live).
        if (obj.name.size() > 0 && obj.name[0] == '<')
            continue;

        for (size_t si = 1; si < obj.sections.size(); ++si) {
            uint64_t key = makeKey(oi, si);
            if (live.count(key))
                continue;

            auto &sec = obj.sections[si];
            if (sec.data.empty())
                continue;

            strippedBytes += sec.data.size();
            ++strippedSections;
            sec.data.clear();
            sec.relocs.clear();
        }
    }

    if (strippedSections > 0)
        err << "dead-strip: removed " << strippedSections << " sections (" << strippedBytes
            << " bytes)\n";
}

} // namespace viper::codegen::linker
