//===----------------------------------------------------------------------===//
//
// Part of the Viper project, under the GNU GPL v3.
// See LICENSE for license information.
//
//===----------------------------------------------------------------------===//
//
// File: src/tools/common/packaging/LinuxRuntimeStubGen.cpp
// Purpose: Generate the Linux self-extracting AppImage runtime stub.
//
// Key invariants:
//   - The shell runtime is POSIX sh and requires only standard base system tools.
//   - Payload bytes are never interpreted by the shell; they are streamed to tar.
//   - The extracted entry point is executed with the caller's argv.
//
// Ownership/Lifetime:
//   - Pure byte generation and structural verification helpers.
//
// Links: LinuxRuntimeStubGen.hpp
//
//===----------------------------------------------------------------------===//

#include "LinuxRuntimeStubGen.hpp"
#include "PkgHash.hpp"
#include "PkgUtils.hpp"

#include <algorithm>
#include <sstream>
#include <string_view>

namespace viper::pkg {
namespace {

std::string shellSingleQuote(std::string_view value) {
    std::string out;
    out.reserve(value.size() + 2);
    out.push_back('\'');
    for (char c : value) {
        if (c == '\'')
            out += "'\\''";
        else
            out.push_back(c);
    }
    out.push_back('\'');
    return out;
}

void validateStubToken(const std::string &value, const char *fieldName) {
    validateSingleLineField(value, fieldName);
    const std::string clean = sanitizePackageRelativePath(value, fieldName);
    if (clean != value)
        throw std::runtime_error(std::string(fieldName) + " was not normalized: " + value);
}

/// @brief Validate an optional payload SHA-256 digest embedded in the stub.
/// @details Empty strings are accepted for standalone stub tests. Complete
///          AppImages generated by buildLinuxAppImage() always provide a
///          lowercase 64-character digest of the appended gzip payload.
/// @param value Digest text to validate.
/// @throws std::runtime_error when @p value is non-empty and not SHA-256 hex.
void validateOptionalSha256(const std::string &value) {
    if (value.empty())
        return;
    if (value.size() != 64)
        throw std::runtime_error("AppImage payload SHA-256 must be 64 hex characters");
    for (char c : value) {
        const bool digit = c >= '0' && c <= '9';
        const bool lower = c >= 'a' && c <= 'f';
        if (!digit && !lower)
            throw std::runtime_error("AppImage payload SHA-256 must be lowercase hexadecimal");
    }
}

std::vector<uint8_t>::const_iterator payloadMarkerIt(const std::vector<uint8_t> &data) {
    const std::string marker = std::string(kLinuxRuntimePayloadMarker) + "\n";
    return std::search(data.begin(),
                       data.end(),
                       reinterpret_cast<const uint8_t *>(marker.data()),
                       reinterpret_cast<const uint8_t *>(marker.data()) + marker.size());
}

/// @brief Extract a single shell assignment value from the generated stub.
/// @details The runtime stub writes simple single-quoted assignments before
///          the payload marker. This helper is intentionally narrow and is used
///          only by verifyLinuxAppImage() to read payload_sha256.
/// @param text Stub text before the binary payload.
/// @param name Assignment name including no trailing equals sign.
/// @return The unquoted assignment value, or an empty string when absent.
std::string shellAssignmentValue(std::string_view text, std::string_view name) {
    const std::string needle = std::string(name) + "='";
    const size_t start = text.find(needle);
    if (start == std::string_view::npos)
        return {};
    size_t pos = start + needle.size();
    std::string out;
    while (pos < text.size()) {
        char c = text[pos++];
        if (c == '\'') {
            if (pos + 2 < text.size() && text[pos] == '\\' && text[pos + 1] == '\'' &&
                text[pos + 2] == '\'') {
                out.push_back('\'');
                pos += 3;
                continue;
            }
            return out;
        }
        out.push_back(c);
    }
    return {};
}

} // namespace

std::vector<uint8_t> buildLinuxRuntimeStub(const LinuxRuntimeStubParams &params) {
    validateStubToken(params.cacheName, "AppImage cache name");
    validateStubToken(params.entryPath, "AppImage entry path");
    validateOptionalSha256(params.payloadSha256);

    std::ostringstream script;
    script
        << "#!/bin/sh\n"
           "set -eu\n"
           "self=$0\n"
           "cache_name="
        << shellSingleQuote(params.cacheName)
        << "\n"
           "entry_path="
        << shellSingleQuote(params.entryPath)
        << "\n"
           "payload_sha256="
        << shellSingleQuote(params.payloadSha256)
        << "\n"
           "case \"$entry_path\" in /*|..|../*|*/../*|*/..) echo \"Unsafe AppImage entry "
           "path: $entry_path\" >&2; exit 2 ;; esac\n"
           "if [ -n \"${XDG_CACHE_HOME:-}\" ]; then\n"
           "    cache_root=$XDG_CACHE_HOME\n"
           "elif [ -n \"${HOME:-}\" ]; then\n"
           "    cache_root=$HOME/.cache\n"
           "else\n"
           "    cache_root=${TMPDIR:-/tmp}\n"
           "fi\n"
           "cache_root=${cache_root%/}/viper\n"
           "case \"$cache_root\" in /*) ;; *) echo \"AppImage cache root must be absolute: "
           "$cache_root\" >&2; exit 2 ;; esac\n"
           "if [ -L \"$cache_root\" ]; then echo \"Refusing symlinked AppImage cache root: "
           "$cache_root\" >&2; exit 2; fi\n"
           "extract_dir=$cache_root/$cache_name\n"
           "stamp_file=$extract_dir/.payload.sha256\n"
           "payload_line=$(awk '/^"
        << kLinuxRuntimePayloadMarker
        << "$/ { print NR + 1; exit }' \"$self\")\n"
           "if [ -z \"$payload_line\" ]; then echo \"AppImage payload marker not found\" >&2; "
           "exit 2; fi\n"
           "case \"${1:-}\" in\n"
           "    --appimage-help) echo \"FUSE-less Viper AppImage options:\"; echo \"  "
           "--appimage-extract  extract payload to ./squashfs-root\"; echo \"  "
           "--appimage-help     show this help\"; exit 0 ;;\n"
           "    --appimage-extract) rm -rf squashfs-root; mkdir -p squashfs-root; tail -n "
           "+$payload_line \"$self\" | tar xzf - -C squashfs-root; echo \"Extracted to "
           "squashfs-root\"; exit 0 ;;\n"
           "esac\n"
           "mkdir -p \"$cache_root\"\n"
           "chmod 700 \"$cache_root\" 2>/dev/null || true\n"
           "if [ -L \"$extract_dir\" ]; then echo \"Refusing symlinked AppImage cache dir: "
           "$extract_dir\" >&2; exit 2; fi\n"
           "case \"${VIPER_APPIMAGE_CLEAN_CACHE:-}\" in 1|true|TRUE|yes|YES) rm -rf "
           "\"$extract_dir\" ;; esac\n"
           "cache_ok=0\n"
           "if [ -x \"$extract_dir/$entry_path\" ]; then\n"
           "    if [ -n \"$payload_sha256\" ]; then\n"
           "        if [ -r \"$stamp_file\" ] && [ \"$(cat \"$stamp_file\")\" = "
           "\"$payload_sha256\" ]; then cache_ok=1; fi\n"
           "    else\n"
           "        cache_ok=1\n"
           "    fi\n"
           "fi\n"
           "if [ \"$cache_ok\" != \"1\" ]; then\n"
           "    tmp_dir=$(mktemp -d \"${cache_root%/}/$cache_name.tmp.XXXXXX\")\n"
           "    trap 'rm -rf \"$tmp_dir\"' EXIT HUP INT TERM\n"
           "    payload_file=$tmp_dir/payload.tar.gz\n"
           "    tail -n +$payload_line \"$self\" > \"$payload_file\"\n"
           "    if [ -n \"$payload_sha256\" ]; then\n"
           "        if command -v sha256sum >/dev/null 2>&1; then\n"
           "            actual_sha256=$(sha256sum \"$payload_file\" | awk '{print $1}')\n"
           "        elif command -v shasum >/dev/null 2>&1; then\n"
           "            actual_sha256=$(shasum -a 256 \"$payload_file\" | awk '{print $1}')\n"
           "        elif command -v openssl >/dev/null 2>&1; then\n"
           "            actual_sha256=$(openssl dgst -sha256 -r \"$payload_file\" | awk '{print "
           "$1}')\n"
           "        else\n"
           "            echo \"No SHA-256 tool available for AppImage verification\" >&2; exit 2\n"
           "        fi\n"
           "        if [ \"$actual_sha256\" != \"$payload_sha256\" ]; then\n"
           "            echo \"AppImage payload checksum mismatch\" >&2; exit 2\n"
           "        fi\n"
           "    fi\n"
           "    tar xzf \"$payload_file\" -C \"$tmp_dir\"\n"
           "    rm -f \"$payload_file\"\n"
           "    chmod +x \"$tmp_dir/$entry_path\" 2>/dev/null || true\n"
           "    if [ -n \"$payload_sha256\" ]; then printf '%s' \"$payload_sha256\" > "
           "\"$tmp_dir/.payload.sha256\"; fi\n"
           "    rm -rf \"$extract_dir.old.$$\"\n"
           "    if [ -e \"$extract_dir\" ]; then mv \"$extract_dir\" \"$extract_dir.old.$$\"; "
           "fi\n"
           "    mv \"$tmp_dir\" \"$extract_dir\"\n"
           "    rm -rf \"$extract_dir.old.$$\"\n"
           "    trap - EXIT HUP INT TERM\n"
           "fi\n"
           "exec \"$extract_dir/$entry_path\" \"$@\"\n"
        << kLinuxRuntimePayloadMarker << "\n";
    const std::string text = script.str();
    return std::vector<uint8_t>(text.begin(), text.end());
}

std::vector<uint8_t> buildLinuxAppImage(const LinuxRuntimeStubParams &params,
                                        const std::vector<uint8_t> &payloadTarGz) {
    if (payloadTarGz.size() < 2 || payloadTarGz[0] != 0x1F || payloadTarGz[1] != 0x8B)
        throw std::runtime_error("AppImage payload must be a gzip-compressed tar archive");
    LinuxRuntimeStubParams checkedParams = params;
    checkedParams.payloadSha256 = sha256Hex(payloadTarGz.data(), payloadTarGz.size());
    std::vector<uint8_t> out = buildLinuxRuntimeStub(checkedParams);
    out.insert(out.end(), payloadTarGz.begin(), payloadTarGz.end());
    return out;
}

bool verifyLinuxAppImage(const std::vector<uint8_t> &data, std::string *err) {
    if (data.size() < 4 || data[0] != '#' || data[1] != '!') {
        if (err)
            *err = "AppImage: missing executable runtime stub\n";
        return false;
    }
    const auto marker = payloadMarkerIt(data);
    if (marker == data.end()) {
        if (err)
            *err = "AppImage: missing payload marker\n";
        return false;
    }
    const std::string markerText = std::string(kLinuxRuntimePayloadMarker) + "\n";
    const auto payload = marker + static_cast<std::ptrdiff_t>(markerText.size());
    const std::string_view stubText(reinterpret_cast<const char *>(data.data()),
                                    static_cast<size_t>(marker - data.begin()));
    const std::string expectedSha = shellAssignmentValue(stubText, "payload_sha256");
    if (!expectedSha.empty()) {
        try {
            validateOptionalSha256(expectedSha);
            const size_t payloadOffset = static_cast<size_t>(payload - data.begin());
            const size_t payloadLen = static_cast<size_t>(data.end() - payload);
            const std::string actualSha = sha256Hex(data.data() + payloadOffset, payloadLen);
            if (actualSha != expectedSha) {
                if (err)
                    *err = "AppImage: payload SHA-256 mismatch\n";
                return false;
            }
        } catch (const std::exception &ex) {
            if (err)
                *err =
                    std::string("AppImage: invalid payload SHA-256 metadata: ") + ex.what() + "\n";
            return false;
        }
    }
    if (payload == data.end() || static_cast<size_t>(data.end() - payload) < 2u ||
        payload[0] != 0x1F || payload[1] != 0x8B) {
        if (err)
            *err = "AppImage: appended payload is not gzip data\n";
        return false;
    }
    return true;
}

} // namespace viper::pkg
