if (NOT DEFINED ILC)
    message(FATAL_ERROR "ILC not set")
endif ()
if (NOT DEFINED IL_FILE)
    message(FATAL_ERROR "IL_FILE not set")
endif ()
if (NOT DEFINED EXPECT)
    message(FATAL_ERROR "EXPECT not set")
endif ()
execute_process(COMMAND ${ILC} -run ${IL_FILE} RESULT_VARIABLE res OUTPUT_VARIABLE out ERROR_VARIABLE err)
if (NOT res EQUAL 0)
    message(FATAL_ERROR "expected zero exit: ${res}\n${err}")
endif ()
string(STRIP "${out}" out)
if (NOT out STREQUAL "${EXPECT}")
    message(FATAL_ERROR "output mismatch: expected '${EXPECT}' got '${out}'")
endif ()
