.TH il-dis 1 "Viper" "viper-il-dis" "User Commands"
.SH NAME
il-dis \- Demonstrate building and serializing IL programmatically
.SH SYNOPSIS
.B il-dis
.SH DESCRIPTION
Constructs a small IL module in memory using the IRBuilder and prints it to stdout. Intended as a developer sample and smoke test.
.SH EXIT STATUS
Always returns 0 unless serialization fails unexpectedly.
.SH SEE ALSO
\fBilc\fR(1)

