' test_convert_fmt.bas — Viper.Core.Convert + Viper.Fmt
PRINT Viper.Core.Convert.ToInt64("42")
PRINT Viper.Core.Convert.ToInt64("-7")
PRINT Viper.Core.Convert.ToDouble("3.14")
PRINT Viper.Core.Convert.ToString_Int(99)
PRINT Viper.Core.Convert.ToString_Double(1.5)
PRINT Viper.Fmt.Int(42)
PRINT Viper.Fmt.Hex(255)
PRINT Viper.Fmt.HexPad(15, 4)
PRINT Viper.Fmt.Bin(5)
PRINT Viper.Fmt.Oct(8)
PRINT Viper.Fmt.Bool(TRUE)
PRINT Viper.Fmt.Bool(FALSE)
PRINT Viper.Fmt.BoolYN(TRUE)
PRINT Viper.Fmt.BoolYN(FALSE)
PRINT Viper.Fmt.IntRadix(10, 2)
PRINT Viper.Fmt.IntPad(7, 3, "0")
PRINT Viper.Fmt.NumFixed(3.14159, 2)
PRINT Viper.Fmt.Ordinal(1)
PRINT Viper.Fmt.Ordinal(2)
PRINT Viper.Fmt.Ordinal(3)
PRINT Viper.Fmt.Ordinal(4)
PRINT Viper.Fmt.IntGrouped(1000000, ",")
PRINT Viper.Fmt.ToWords(1)
PRINT Viper.Fmt.Currency(9.99, 2, "$")
PRINT "done"
END
