//===----------------------------------------------------------------------===//
//
// Part of the Viper project, under the MIT License.
// See LICENSE for license information.
//
//===----------------------------------------------------------------------===//
//
// File: src/frontends/basic/lower/common/BuiltinUtils.cpp
// Purpose: Materialise the registry-backed dispatcher used to lower BASIC
//          builtin calls.
// Key invariants: Each builtin name resolves to at most one handler and the
//                 registry initialises exactly once per process.
// Ownership/Lifetime: Relies on process-wide registration tables and does not
//                     allocate persistent state beyond handler bindings.
// Links: docs/basic-language.md, docs/codemap.md
//
//===----------------------------------------------------------------------===//

#include "frontends/basic/lower/common/BuiltinUtils.hpp"

#include "frontends/basic/BuiltinRegistry.hpp"
#include "frontends/basic/DiagnosticEmitter.hpp"
#include "frontends/basic/builtins/StringBuiltins.hpp"
#include "frontends/basic/lower/BuiltinCommon.hpp"

#include <initializer_list>
#include <string>
#include <string_view>

namespace il::frontends::basic::lower::common
{
namespace
{
constexpr std::string_view kDiagMissingBuiltinEmitter = "B4004";

using Builtin = BuiltinCallExpr::Builtin;

/// @brief Lower string-centric BASIC builtins through specialised handlers.
/// @details Consults the string builtin registry to locate an implementation
///          that understands argument bounds and return typing.  When a builtin
///          lacks a specialised handler or the arity check fails, control falls
///          back to the generic lowering pipeline so behaviour remains
///          consistent.
/// @param ctx Context wrapper that exposes the current call expression.
/// @return Lowered r-value describing the builtin result.
Lowerer::RVal lowerStringBuiltin(BuiltinLowerContext &ctx)
{
    const auto *stringSpec = builtins::findBuiltin(ctx.info().name);
    if (!stringSpec)
        return lowerGenericBuiltin(ctx);

    const std::size_t argCount = ctx.call().args.size();
    if (argCount < static_cast<std::size_t>(stringSpec->minArity) ||
        argCount > static_cast<std::size_t>(stringSpec->maxArity))
        return lowerGenericBuiltin(ctx);

    builtins::LowerCtx strCtx(ctx.lowerer(), ctx.call());
    il::core::Value resultValue = stringSpec->fn(strCtx, strCtx.values());
    return {resultValue, strCtx.resultType()};
}

/// @brief Lower math builtins using the shared generic dispatcher.
/// @details Math functions currently reuse the generic lowering logic, so this
///          helper simply forwards the call.  The indirection keeps the
///          registration site self-documenting and prepares for future
///          specialisation.
/// @param ctx Builtin lowering context describing the invocation.
/// @return Lowered r-value produced by the generic lowering path.
Lowerer::RVal lowerMathBuiltin(BuiltinLowerContext &ctx)
{
    return lowerGenericBuiltin(ctx);
}

/// @brief Lower numeric conversion builtins.
/// @details Delegates to @ref lowerConversionBuiltinImpl so conversions share
///          the canonical implementation for type coercions.  The wrapper
///          exists so registration sites remain readable.
/// @param ctx Builtin lowering context describing the invocation.
/// @return Lowered r-value produced by the conversion helper.
Lowerer::RVal lowerConversionBuiltin(BuiltinLowerContext &ctx)
{
    return lowerConversionBuiltinImpl(ctx);
}

/// @brief Lower builtins that have no specialised implementation.
/// @details Dispatches to the generic lowering logic that emits an indirect call
///          following the runtime registry metadata.  Used as the catch-all for
///          the majority of BASIC builtins.
/// @param ctx Builtin lowering context describing the invocation.
/// @return Lowered r-value generated by the generic dispatcher.
Lowerer::RVal lowerDefaultBuiltin(BuiltinLowerContext &ctx)
{
    return lowerGenericBuiltin(ctx);
}

/// @brief Register a lowering handler for a set of builtin identifiers.
/// @details Iterates the supplied builtin list and records @p handler for each
///          name in the global registry.  Consolidating the loop ensures that
///          handler registration stays uniform across families of builtins.
/// @param handler Function pointer capable of lowering each builtin.
/// @param builtins Collection of builtin identifiers to bind.
void registerFamilyHandlers(BuiltinHandler handler, std::initializer_list<Builtin> builtins)
{
    for (Builtin builtin : builtins)
        register_builtin(getBuiltinInfo(builtin).name, handler);
}

/// @brief Install fallback handlers for every builtin without a special case.
/// @details Iterates the builtin enumeration and binds
///          @ref lowerDefaultBuiltin except for file I/O intrinsics that are
///          emitted through dedicated lowering routines elsewhere.
void registerDefaultHandlers()
{
    for (std::size_t ordinal = 0; ordinal <= static_cast<std::size_t>(Builtin::Loc); ++ordinal)
    {
        auto builtin = static_cast<Builtin>(ordinal);
        switch (builtin)
        {
            case Builtin::Eof:
            case Builtin::Lof:
            case Builtin::Loc:
                break;
            default:
                register_builtin(getBuiltinInfo(builtin).name, &lowerDefaultBuiltin);
                break;
        }
    }
}

/// @brief Lazily initialise the builtin lowering registry.
/// @details Uses a static guard to register the default and specialised
///          handlers exactly once per process.  Subsequent calls become no-ops
///          while still guaranteeing that the registry has been populated.
void ensureBuiltinHandlers()
{
    static const bool initialized = []
    {
        registerDefaultHandlers();

        registerFamilyHandlers(&lowerStringBuiltin,
                               {Builtin::Len,
                                Builtin::Mid,
                                Builtin::Left,
                                Builtin::Right,
                                Builtin::Str,
                                Builtin::Instr,
                                Builtin::Ltrim,
                                Builtin::Rtrim,
                                Builtin::Trim,
                                Builtin::Ucase,
                                Builtin::Lcase,
                                Builtin::Chr,
                                Builtin::Asc,
                                Builtin::InKey,
                                Builtin::GetKey});

        registerFamilyHandlers(&lowerConversionBuiltin,
                               {Builtin::Val, Builtin::Cint, Builtin::Clng, Builtin::Csng});

        registerFamilyHandlers(&lowerMathBuiltin,
                               {Builtin::Cdbl,
                                Builtin::Int,
                                Builtin::Fix,
                                Builtin::Round,
                                Builtin::Sqr,
                                Builtin::Abs,
                                Builtin::Floor,
                                Builtin::Ceil,
                                Builtin::Sin,
                                Builtin::Cos,
                                Builtin::Pow,
                                Builtin::Rnd});

        return true;
    }();
    (void)initialized;
}

} // namespace

/// @brief Lower a BASIC builtin call into IL.
/// @details Ensures the handler registry is initialised, constructs a
///          @ref BuiltinLowerContext, and dispatches to the registered handler.
///          When no handler is available the function emits a diagnostic (when
///          possible) and returns a zero-valued result so downstream passes can
///          continue operating.
/// @param lowerer Active lowering context used to emit IL.
/// @param call AST node describing the builtin invocation.
/// @return Lowered r-value or a zero substitute when no handler exists.
Lowerer::RVal lowerBuiltinCall(Lowerer &lowerer, const BuiltinCallExpr &call)
{
    ensureBuiltinHandlers();

    BuiltinLowerContext ctx(lowerer, call);
    if (BuiltinHandler handler = find_builtin(ctx.info().name))
        return handler(ctx);

    if (auto *diag = lowerer.diagnosticEmitter())
    {
        ctx.setCurrentLoc(call.loc);
        diag->emit(il::support::Severity::Error,
                   std::string(kDiagMissingBuiltinEmitter),
                   call.loc,
                   0,
                   "no emitter registered for builtin call");
    }

    return ctx.makeZeroResult();
}

/// @brief Expose handler initialisation for unit tests.
/// @details Invokes @ref ensureBuiltinHandlers so tests can rely on the same
///          registration logic as production code without duplicating
///          boilerplate.
void ensureBuiltinHandlersForTesting()
{
    ensureBuiltinHandlers();
}

} // namespace il::frontends::basic::lower::common
