//===----------------------------------------------------------------------===//
//
// Part of the Viper project, under the GNU GPL v3.
// See LICENSE for license information.
//
//===----------------------------------------------------------------------===//
//
// File: src/il/runtime/classes/RuntimeClasses.cpp
// Purpose: Build the runtime class catalog by macro-expanding the declarative
//          table in RuntimeClasses.inc into C++ descriptors.
// Invariants:
//   - Catalog built once in a thread-safe manner (function-local static).
//   - All strings are static literals; vectors own their element storage.
// Notes:
//   - Receiver is arg0; signatures omit the receiver per spec comment in HPP.
// Links:
//   - docs/il-guide.md#reference
//   - docs/codemap.md
//   - src/il/runtime/classes/RuntimeClasses.inc

/// @file
/// @brief Builds the runtime class catalog from declarative .inc data.
/// @details Expands the RuntimeClasses.inc table into concrete descriptors used
///          by the IL runtime for class, property, and method metadata.

#include "il/runtime/classes/RuntimeClasses.hpp"

#include <algorithm>
#include <cctype>
#include <utility>

namespace il::runtime
{

namespace
{
// Macro helpers to materialize descriptor elements from the .inc file.
#define RUNTIME_PROP(_name, _type, _getter, _setter)                                               \
    ::il::runtime::RuntimeProperty                                                                 \
    {                                                                                              \
        (_name), (_type), (_getter), (_setter), ((_setter) == nullptr)                             \
    }

#define RUNTIME_PROPS(...)                                                                         \
    std::vector<::il::runtime::RuntimeProperty>                                                    \
    {                                                                                              \
        __VA_ARGS__                                                                                \
    }

#define RUNTIME_METHOD(_name, _sig, _target)                                                       \
    ::il::runtime::RuntimeMethod                                                                   \
    {                                                                                              \
        (_name), (_sig), (_target)                                                                 \
    }

#define RUNTIME_METHODS(...)                                                                       \
    std::vector<::il::runtime::RuntimeMethod>                                                      \
    {                                                                                              \
        __VA_ARGS__                                                                                \
    }

#define RUNTIME_CLASS(_qname, _typeId, _layout, _ctor, _props, _methods)                           \
    catalog.emplace_back(::il::runtime::RuntimeClass{(_qname),                                     \
                                                     (_layout),                                    \
                                                     (_ctor),                                      \
                                                     ::il::runtime::RuntimeTypeId::_typeId,        \
                                                     (_props),                                     \
                                                     (_methods)});
} // namespace

/// @brief Return the process-wide runtime class catalog.
/// @details Builds the catalog once using a function-local static initialized
///          from RuntimeClasses.inc. The returned vector is immutable and
///          safe to share across threads.
/// @return Reference to the runtime class catalog.
const std::vector<RuntimeClass> &runtimeClassCatalog()
{
    static const std::vector<RuntimeClass> catalog_init = []
    {
        std::vector<RuntimeClass> catalog;
        catalog.reserve(8); // initial seed; grows as we add classes

// Expand runtime class declarations (generated by rtgen from runtime.def)
#include "il/runtime/RuntimeClasses.inc"

        return catalog;
    }();
    return catalog_init;
}

const RuntimeClass *findRuntimeClassByQName(std::string_view qname)
{
    const auto &catalog = runtimeClassCatalog();
    for (const auto &c : catalog)
    {
        std::string_view cname{c.qname};
        if (qname.size() != cname.size())
        {
            continue;
        }
        bool match = std::equal(qname.begin(),
                                qname.end(),
                                cname.begin(),
                                cname.end(),
                                [](char a, char b)
                                {
                                    return std::toupper(static_cast<unsigned char>(a)) ==
                                           std::toupper(static_cast<unsigned char>(b));
                                });
        if (match)
        {
            return &c;
        }
    }
    return nullptr;
}

} // namespace il::runtime
